name: Publish Image
on:
  release:
    types: [published]
jobs:
  push_to_dockerhub:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-docker-hub-namespace/my-docker-repo-name
          tag_with_ref: true
